### ISSUE TITLE
Error on enabling "Include Units in Dimension Label" check box in Rebar Shape Cut list 

### ISSUE THREAD

**Issue by ShivCharanSharma** [amrit3701/FreeCAD-Reinforcement#153]
`
Traceback (most recent call last):
  File "/home/shiv/.FreeCAD/Mod/Reinforcement/RebarShapeCutList/MainRebarShapeCutList.py", line 278, in accept
    getRebarShapeCutList(
  File "/home/shiv/.FreeCAD/Mod/Reinforcement/RebarShapeCutList/RebarShapeCutListfunc.py", line 1169, in getRebarShapeCutList
    rebar_svg = getRebarShapeSVG(
  File "/home/shiv/.FreeCAD/Mod/Reinforcement/RebarShapeCutList/RebarShapeCutListfunc.py", line 928, in getRebarShapeSVG
    edge_length += rebar_dimension_units
TypeError: can only concatenate str (not "float") to str
`

OS: Ubuntu 20.04.2 LTS (ubuntu:GNOME/ubuntu)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.23756 (Git) AppImage
Build type: Release
Branch: master
Hash: 9c6e9184930a52b165a0b7274e3a45d1006bfe67
Python version: 3.8.6
Qt version: 5.12.5
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/India (en_IN)

**Comment by luzpaz** [comment]
For readability, please put code or errors/warnings in code markdown. Thanks

**Comment by luzpaz** [comment]
@amrit3701 can you reproduce?

**Comment by amrit3701** [comment]
Issue already fixed. Closing ticket...
