### ISSUE TITLE
Error while editing "Bent-Shape" Rebar

### ISSUE THREAD

**Issue by balrobs** [amrit3701/FreeCAD-Reinforcement#203]
when I
1. create a Bent-Shape Rebar with the "Bent-Shape Rebar"-dialog
2. then double-click on the created Rebar-Object in the object-tree
I see this error:
```
09:14:23  TypeError: 'Base.Quantity' object cannot be interpreted as an integer
09:14:23  pyException: Traceback (most recent call last):
  File "C:\Program Files\FreeCAD_weekly-builds-37436-conda-Windows-x86_64-py311\Mod\BIM\ArchRebar.py", line 437, in setEdit
    module.editDialog(vobj)
  File "C:\Users\balrobs\AppData\Roaming\FreeCAD\Mod\Reinforcement\.\BentShapeRebar.py", line 692, in editDialog
    obj.form.bentAngle.setValue(vobj.Object.BentAngle)
<class 'OverflowError'>: <unknown exception data>
```

**Comment by balrobs** [comment]
Thx for merging!
