### ISSUE TITLE
TypeError in Reinforcement Drawing Dimensioning

### ISSUE THREAD

**Issue by balrobs** [amrit3701/FreeCAD-Reinforcement#217]
After clicking the Finishing-Button in the "Reinforcement Drawing Dimensioning"-dialog I see this error:
```
09:35:30  Traceback (most recent call last):
09:35:30    File "C:\Users\balrobs\AppData\Roaming\FreeCAD\Mod\Reinforcement\.\ReinforcementDrawing\MainReinforcementDrawingDimensioning.py", line 574, in nextButtonClicked
09:35:30      self.accept()
09:35:30    File "C:\Users\balrobs\AppData\Roaming\FreeCAD\Mod\Reinforcement\.\ReinforcementDrawing\MainReinforcementDrawingDimensioning.py", line 773, in accept
09:35:30      FreeCADGui.doCommand(
09:35:30    File "<string>", line 1, in <module>
09:35:30    File "C:\Users\balrobs\AppData\Roaming\FreeCAD\Mod\Reinforcement\.\ReinforcementDrawing\make_reinforcement_drawing.py", line 293, in makeStructuresReinforcementDrawing
09:35:30      struct_drawing_page_dict[structure] = makeReinforcementDrawing(
09:35:30                                            ^^^^^^^^^^^^^^^^^^^^^^^^^
09:35:30    File "C:\Users\balrobs\AppData\Roaming\FreeCAD\Mod\Reinforcement\.\ReinforcementDrawing\make_reinforcement_drawing.py", line 151, in makeReinforcementDrawing
09:35:30      reinforcement_drawing_page = makeReinforcementDrawingObject(template_file)
09:35:30                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
09:35:30    File "C:\Users\balrobs\AppData\Roaming\FreeCAD\Mod\Reinforcement\.\ReinforcementDrawing\ReinforcementDrawingView.py", line 477, in makeReinforcementDrawingObject
09:35:30      drawing_page.addView(reinforcement_drawing_view)
09:35:30  TypeError: argument 1 must be TechDraw.DrawView, not FeaturePython
```

OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37543 (Git)
Build type: Release
Branch: main
Hash: 3eb45b045cdda9d5bfe11baba2567a1df90f064c
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * Reinforcement

**Comment by balrobs** [comment]
the error can be reproduced with FreeCAD 0.21.2 for Windows10

**Comment by balrobs** [comment]
with FreeCAD 0.20.2 everything works fine!
![beam](https://github.com/amrit3701/FreeCAD-Reinforcement/assets/73989799/2d1bf506-c848-4dc5-971b-2dfc000dd667)
so the error must be caused by a change in TechDraw between the versions 0.20.2 and 0.21.
I would like to fix this error so that this feature also works in the latest FreeCAD version, unfortunately I can't get any further with my limited knowledge. Therefore I turn to you, @amrit3701 and @WandererFan because I think you are the ones that can eventually help me.
Thank you in advance for any helpful tips that can bring me further
balrobs

**Comment by luzpaz** [comment]
@amrit3701 any chance you can respond ?

**Comment by Sonk900** [comment]
Hi, I have the same error. When I create dimensions, it gives an error and nothing is displayed on the drawing sheet. Same thing when I create a BOM, the table is created but nothing is inserted in the drawing.
FreeCAD 1.0.1
Windows 11 Pro

And on version 0.20 everything works correctly.
