### ISSUE TITLE
Opening BIM WB when Reinforcement WB is installed causes problems

### ISSUE THREAD

**Issue by hasecilu** [amrit3701/FreeCAD-Reinforcement#220]
![image](https://github.com/user-attachments/assets/50e3b991-ac74-43e8-9ead-a5fe4ece807b)

![image](https://github.com/user-attachments/assets/3c0dbe3a-8d81-479b-8e66-26ab25240dd9)

```python
14:50:38  partially initialized module 'bimcommands' has no attribute 'BimIfcQuantities' (most likely due to a circular import)
14:50:38  Traceback (most recent call last):
  File "/opt/FreeCAD_1_0_Qt6/Mod/BIM/InitGui.py", line 51, in Initialize
    self.createTools()
  File "/opt/FreeCAD_1_0_Qt6/Mod/BIM/InitGui.py", line 69, in createTools
    import bimcommands
  File "/opt/FreeCAD_1_0_Qt6/Mod/BIM/bimcommands/__init__.py", line 10, in <module>
    from . import *

14:52:22  'BIMWorkbench' object has no attribute 'draftingtools'
14:52:22  Traceback (most recent call last):
  File "/opt/FreeCAD_1_0_Qt6/Mod/BIM/InitGui.py", line 514, in Activated
    BimWatcher(self.draftingtools + self.annotationtools, "2D geometry"),
               ^^^^^^^^^^^^^^^^^^

14:52:22  Traceback (most recent call last):
  File "/opt/FreeCAD_1_0_Qt6/Mod/Draft/draftutils/todo.py", line 138, in doTasks
    f(arg)
  File "/opt/FreeCAD_1_0_Qt6/Mod/BIM/BimStatus.py", line 148, in setStatusIcons
    from bimcommands import BimViews
  File "/opt/FreeCAD_1_0_Qt6/Mod/BIM/bimcommands/__init__.py", line 10, in <module>
    from . import *
AttributeError: partially initialized module 'bimcommands' has no attribute 'BimIfcQuantities' (most likely due to a circular import)

14:52:22  Traceback (most recent call last):
  File "/opt/FreeCAD_1_0_Qt6/Mod/Draft/draftutils/todo.py", line 138, in doTasks
    f(arg)
  File "/opt/FreeCAD_1_0_Qt6/Mod/BIM/BimStatus.py", line 148, in setStatusIcons
    from bimcommands import BimViews
  File "/opt/FreeCAD_1_0_Qt6/Mod/BIM/bimcommands/__init__.py", line 10, in <module>
    from . import *
AttributeError: partially initialized module 'bimcommands' has no attribute 'BimIfcQuantities' (most likely due to a circular import)
```

Self-compiled version
```
OS: Arch Linux (Hyprland/hyprland)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36460 +2183 (Git)
Build type: Release
Branch: main
Hash: 1cc3c4f3ecdd6634800fd4db1725e8a24dfd07a0
Python 3.12.5, Qt 6.7.2, Coin 4.0.3, Vtk 9.3.1, OCC 7.7.2
Locale: Spanish/Mexico (es_MX)
Stylesheet/Theme/QtStyle: OpenDark.qss/OpenDark/
Installed mods: 
  * FreeCAD-Reinforcement
```
Also happens on latest AppImage

**Comment by luzpaz** [comment]
@amrit3701 :wave:

**Comment by yorikvanhavre** [comment]
Ping @amrit3701 - This turns the WB unusable in FreeCAD 1.0

**Comment by amrit3701** [comment]
Issue Fixed: https://github.com/amrit3701/FreeCAD-Reinforcement/commit/62317582542d80dba15dbae2a02902b7b5fe143e
